"""``redacted_thinking.data`` is provider-encrypted ciphertext, not prose (issue #374,
ADR-0057 D6.2, amending ADR-0051's #323 amendment).

The #323 amendment inverted the blinder's content-block walk to deny-by-default: every
block-type falls through to the generic walk unless its key is in the closed
``_BLOCK_NON_HOP_KEYS`` set. That amendment named ``redacted_thinking`` in its covered-set
prose but never added its ``data`` field to the exclusion set, so the generic walk (and the
leak gate's exhaustive ``_collect_text``) both treat ``data`` as an ordinary string leaf.
``data`` is the provider's own encrypted reasoning blob, handed back byte-exact at decrypt
time and never regenerated by anything Blindfold does -- rewriting even one byte (a
deterministic L1/L2 hit, a provisional surrogate, an L3 mint) corrupts the request
irrecoverably, and a coincidental substring match inside the ciphertext is not a leak: it
cannot contain a real value Blindfold is responsible for unless the *request* that produced
it leaked, which the gate checks independently on that earlier, unencrypted hop. This module
pins ``data`` as a declared non-hop on both the blinder and the leak gate, symmetric with
``signature`` (ADR-0051).
"""

from blindfold.engine import (
    ExchangeSession,
    blindfold_payload,
    leak_gate,
    restore_response,
)
from blindfold.l3 import CandidateSpan, L3Adjudication, L3Detector
from blindfold.review import ReviewInbox
from blindfold.surrogates import SurrogateMapping


def _mapping() -> SurrogateMapping:
    return SurrogateMapping.from_pairs([("Anna Schmidt", "Berta Vogel")])


class _RecordingAdjudicator:
    """Records every candidate text it is asked to adjudicate, confirming none --
    AC2 needs a call count of zero over ``redacted_thinking.data``, not just a clean
    output, so this stub exists purely to prove the adjudicator seam was never
    reached for it."""

    def __init__(self) -> None:
        self.calls: list[str] = []

    def adjudicate(self, candidate: CandidateSpan) -> L3Adjudication:
        self.calls.append(candidate.text)
        return L3Adjudication(is_entity=False)


def test_redacted_thinking_data_is_byte_identical_and_leak_gate_stays_clean():
    # The ciphertext coincidentally contains a seeded L2 term ("Anna Schmidt") at a
    # genuine word boundary (flanked by base64 padding "="), so it is a real hit
    # under both the blinder's deterministic match and the gate's word-boundary
    # `_real_value_pattern` -- exactly the collision the agent brief names. Pre-fix,
    # the generic walk rewrites this to the surrogate (corrupting the ciphertext);
    # even with the blinder alone fixed, the gate's exhaustive `_collect_text` walk
    # would still fail-close on this same coincidental hit unless it is excluded too.
    mapping = _mapping()
    ciphertext = "EmVhbm5hIHNjaG1pZHQ=Anna Schmidt=b3BhcXVlLWNpcGhlcnRleHQ="
    adjudicator = _RecordingAdjudicator()
    detector = L3Detector(adjudicator)
    inbox = ReviewInbox()

    payload = {
        "model": "m",
        "messages": [
            {
                "role": "assistant",
                "content": [
                    {"type": "redacted_thinking", "data": ciphertext},
                ],
            }
        ],
    }

    blinded, _session = blindfold_payload(payload, mapping, detector, inbox)

    block = blinded["messages"][0]["content"][0]
    assert block["data"] == ciphertext

    # AC2: L3 candidate production must never be invoked over this field.
    assert adjudicator.calls == []

    # Scope item 2 (symmetry): the leak gate must not fail-close on the coincidental
    # substring match inside declared-non-hop ciphertext.
    leak_gate(blinded, mapping, inbox)


def test_a_sibling_thinking_block_in_the_same_request_is_still_blindfolded():
    # AC3: the exclusion is type-specific -- a plain (non-redacted) `thinking`
    # block's own prose field must still be blindfolded and gated exactly as
    # today, even alongside a `redacted_thinking` block in the same request.
    mapping = _mapping()
    ciphertext = "b3BhcXVlLWNpcGhlcnRleHQ="

    payload = {
        "model": "m",
        "messages": [
            {
                "role": "assistant",
                "content": [
                    {
                        "type": "thinking",
                        "thinking": "I should mention Anna Schmidt in the summary.",
                        "signature": "sig-opaque-blob",
                    },
                    {"type": "redacted_thinking", "data": ciphertext},
                ],
            }
        ],
    }

    blinded, _session = blindfold_payload(payload, mapping)

    thinking_block, redacted_block = blinded["messages"][0]["content"]
    assert "Anna Schmidt" not in thinking_block["thinking"]
    assert mapping.surrogate_for("Anna Schmidt") in thinking_block["thinking"]
    assert thinking_block["signature"] == "sig-opaque-blob"
    assert redacted_block["data"] == ciphertext

    leak_gate(blinded, mapping)


def test_restore_leaves_redacted_thinking_data_byte_identical():
    # AC4: restore over ciphertext is the same corruption in the other direction --
    # a surrogate-shaped substring coincidentally present in `data` must never be
    # rewritten back to a real value either.
    mapping = _mapping()
    session = ExchangeSession()
    surrogate = mapping.surrogate_for("Anna Schmidt")
    session.record(surrogate, "Anna Schmidt")

    ciphertext = f"b3BhcXVlLQ=={surrogate}=Y2lwaGVydGV4dA=="
    response = {
        "id": "msg_1",
        "type": "message",
        "role": "assistant",
        "content": [{"type": "redacted_thinking", "data": ciphertext}],
    }

    restored = restore_response(response, session)

    assert restored["content"][0]["data"] == ciphertext
