"""Generate `src/blindfold/common_english_words.txt` (ADR-0023, "Update (run-14
gate decisions)", issue #362): the dictionary-informed-clearing wordlist.

`wordfreq` is a **dev-dependency only** (the `wordlist` group) -- it is never
imported at runtime. Upstream froze its data permanently in September 2024
(its own SUNSET.md: post-2021 web text is too LLM-polluted to measure human
usage), so there is no update stream a runtime dependency would buy, only
supply-chain surface inside a privacy proxy's detection path. Re-run this
script and commit the diff if a maintained successor to `wordfreq` ever
appears; that is the single swap point the ADR names.

Usage (from a checkout with the `wordlist` dependency group installed):

    uv run --group wordlist python scripts/generate_common_english_words.py
"""

from __future__ import annotations

import re
from importlib.metadata import version
from pathlib import Path

import wordfreq

# Zipf threshold (log10 of occurrences per billion words, wordfreq's own
# frequency unit): 3.3 comfortably includes ordinary workplace/software
# vocabulary (e.g. "repository" at 3.43, "visibility" at 3.78) while staying
# well short of the full ~40k-entry "best" wordlist -- a threshold, not a
# top-N count, per the ADR's own instruction to record the choice.
ZIPF_THRESHOLD = 3.3

# English only (ADR-0033's German surname-homograph precedent: German
# capitalises every noun, so a German wordlist would gut case-inconsistency
# evidence for exactly the class this heuristic exists to protect).
LANGUAGE = "en"

# Alphabetic tokens only, length >= 3: excludes numerals, contractions,
# hyphenated/apostrophe'd forms, and the noisiest two-letter tail (chat
# abbreviations, initials) `wordfreq`'s frequency list otherwise carries.
_WORD_RE = re.compile(r"[a-z]+")
_MIN_LENGTH = 3

_OUTPUT_PATH = Path(__file__).parent.parent / "src" / "blindfold" / "common_english_words.txt"


def generate() -> list[str]:
    frequency_dict = wordfreq.get_frequency_dict(LANGUAGE, wordlist="best")
    words = sorted(
        word
        for word in frequency_dict
        if _WORD_RE.fullmatch(word)
        and len(word) >= _MIN_LENGTH
        and wordfreq.zipf_frequency(word, LANGUAGE) >= ZIPF_THRESHOLD
    )
    return words


def main() -> None:
    words = generate()
    wordfreq_version = version("wordfreq")
    header_lines = [
        '# Common-English wordlist (ADR-0023, "Update (run-14 gate decisions)", issue',
        "# #362): dictionary-informed clearing's fifth-condition third clearing path.",
        "# A single-token Title-Case run whose casefolded form appears here, with at",
        "# least one prose-lowercase payload occurrence, clears L3 candidacy -- never",
        "# for multi-word runs, never when lowercase evidence is absent entirely.",
        "#",
        f'# Generated by scripts/generate_common_english_words.py from wordfreq {wordfreq_version}\'s',
        f'# "best" English wordlist, Zipf frequency threshold {ZIPF_THRESHOLD}, alphabetic',
        f"# tokens of length >= {_MIN_LENGTH} only. English only by design (ADR-0033's",
        "# German surname-homograph precedent). Static and vendored: wordfreq froze its",
        "# data in September 2024 (its own SUNSET.md), so this file does not go stale on",
        "# a schedule -- re-run the generation script only if a maintained successor to",
        "# wordfreq appears.",
        "#",
        "# One casefolded word per line. Blank lines and #-comments ignored (same",
        "# loader contract as seeded_allowlist.txt / l3_stopwords_en_de.txt).",
        "#",
        f"# {len(words)} entries.",
        "",
    ]
    header = "\n".join(header_lines)
    _OUTPUT_PATH.write_text(header + "\n" + "\n".join(words) + "\n", encoding="utf-8")
    print(f"Wrote {len(words)} words to {_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
