"""OpenBao Transit client — encryption-as-a-service seam (ADR-0008 / issue #10).

Keys live in OpenBao; the app process never holds key material. Callers pass in
a pre-configured ``httpx.Client`` (or ``httpx.AsyncClient``) so tests can stub
the network boundary with ``httpx.MockTransport``.

Transit key names (decided in HITL comment on issue #10):
  blindfold-mapping        encrypt/decrypt real values
  blindfold-blind-index    deterministic HMAC for equality lookups (blind index)
"""

from __future__ import annotations

import base64
from typing import Any

import httpx

from .status import DependencyHealth

_MAPPING_KEY = "blindfold-mapping"
_BLIND_INDEX_KEY = "blindfold-blind-index"
_HMAC_ALGORITHM = "sha2-256"

# OpenBao/Vault Transit's own wire format for ciphertext -- fixed by the server, never
# generated by this client. Public so a startup guard (ADR-0045 §6, issue #232) can
# recognise a value written by Transit even when the Local key cipher is what's
# currently configured (mirrors mapping_cipher.SCHEME_PREFIX, ADR-0045 §3).
CIPHERTEXT_PREFIX = "vault:v1:"


class TransitError(RuntimeError):
    """A named Transit-boundary failure (issue #364), mirroring
    :class:`~blindfold.upstream.UpstreamError`'s scrubbed-by-construction contract.

    Raised on a non-200 response or a 200 response missing the expected
    ``data.<field>`` shape -- previously these surfaced as a bare, unnamed
    ``KeyError`` from indexing straight into the response body (issue #364's
    crown-jewel-seam repro: a stub/misconfigured/rewrapped-key Transit answering
    with no ``plaintext`` field crashed decrypt with no named failure mode).
    ``message`` never carries the ciphertext or plaintext value -- only the HTTP
    status and the operation name.
    """

    def __init__(self, operation: str, status_code: int, message: str) -> None:
        self.operation = operation
        self.status_code = status_code
        super().__init__(message)


class TransitClient:
    """Synchronous OpenBao Transit client.

    Inject via ``http=httpx.Client(transport=httpx.MockTransport(...))`` in tests.
    Production wiring reads ``BLINDFOLD_OPENBAO_ADDR`` / ``BLINDFOLD_OPENBAO_TOKEN``
    from the environment and constructs a real httpx.Client.
    """

    def __init__(
        self,
        addr: str,
        token: str,
        http: httpx.Client | None = None,
        mapping_key: str = _MAPPING_KEY,
        blind_index_key: str = _BLIND_INDEX_KEY,
    ) -> None:
        self._addr = addr.rstrip("/")
        self._token = token
        self._mapping_key = mapping_key
        self._blind_index_key = blind_index_key
        self._http = http or httpx.Client(
            base_url=self._addr,
            headers={"X-Vault-Token": self._token},
        )

    def _extract_data_field(self, resp: httpx.Response, *, operation: str, field: str) -> Any:
        """Return ``resp.json()["data"][field]``, or raise a named :class:`TransitError`.

        Covers both failure shapes at this one seam (issue #364): a non-200
        response (Transit denied or errored the call), and a 200 response whose
        body doesn't carry the expected field (a stub or misconfigured Transit
        answering the wrong shape) -- previously the second case surfaced as an
        unnamed ``KeyError`` from indexing straight into the body.
        """
        if resp.status_code != 200:
            raise TransitError(
                operation=operation,
                status_code=resp.status_code,
                message=f"transit {operation} failed: HTTP {resp.status_code}",
            )
        try:
            return resp.json()["data"][field]
        except (KeyError, TypeError, ValueError) as exc:
            raise TransitError(
                operation=operation,
                status_code=resp.status_code,
                message=(
                    f"transit {operation} failed: HTTP {resp.status_code} response "
                    f"missing data.{field}"
                ),
            ) from exc

    def encrypt(self, plaintext: str) -> str:
        """Encrypt ``plaintext`` via Transit; returns ciphertext (vault:v1:…)."""
        encoded = base64.b64encode(plaintext.encode()).decode()
        resp = self._http.post(
            f"{self._addr}/v1/transit/encrypt/{self._mapping_key}",
            json={"plaintext": encoded},
            headers={"X-Vault-Token": self._token},
        )
        return self._extract_data_field(resp, operation="encrypt", field="ciphertext")

    def decrypt(self, ciphertext: str) -> str:
        """Decrypt ``ciphertext`` via Transit; returns the original plaintext string."""
        resp = self._http.post(
            f"{self._addr}/v1/transit/decrypt/{self._mapping_key}",
            json={"ciphertext": ciphertext},
            headers={"X-Vault-Token": self._token},
        )
        encoded = self._extract_data_field(resp, operation="decrypt", field="plaintext")
        return base64.b64decode(encoded).decode()

    def is_root_token(self) -> bool:
        """Self-lookup the configured token; True iff it carries the ``root`` policy.

        Used by the startup guard (SEC-2, issue #44): the proxy refuses to run against
        a root Transit token without the explicit ``BLINDFOLD_ALLOW_ROOT_TRANSIT_TOKEN``
        opt-in (ADR-0047 §13), since root bypasses every policy
        (blindfold-proxy/-human/-admin) the store's RBAC separation depends on.
        """
        resp = self._http.get(
            f"{self._addr}/v1/auth/token/lookup-self",
            headers={"X-Vault-Token": self._token},
        )
        policies = self._extract_data_field(resp, operation="is_root_token", field="policies")
        return policies == ["root"]

    def health_check(self) -> DependencyHealth:
        """Lightweight OpenBao liveness probe (issue #92) -- GET ``/v1/sys/health``.

        Unauthenticated (no token header needed) -- confirms the daemon answers
        without touching key material. The failure detail is a fixed, scrubbed
        string, never the httpx exception's own text.
        """
        try:
            response = self._http.get(f"{self._addr}/v1/sys/health")
            response.raise_for_status()
        except httpx.HTTPError:
            return DependencyHealth(healthy=False, detail="openbao unreachable")
        return DependencyHealth(healthy=True)

    def blind_index(self, value: str) -> str:
        """Return the HMAC digest of ``value`` for equality lookups over ciphertext columns."""
        encoded = base64.b64encode(value.encode()).decode()
        resp = self._http.post(
            f"{self._addr}/v1/transit/hmac/{self._blind_index_key}/{_HMAC_ALGORITHM}",
            json={"input": encoded},
            headers={"X-Vault-Token": self._token},
        )
        return self._extract_data_field(resp, operation="blind_index", field="hmac")
